
FROM node:21-alpine3.18 as build

# Installation d'Angular CLI
RUN echo "Installation d'Angular CLI..."
RUN npm install @angular/cli

WORKDIR /usr/app

# Copier les fichiers de votre application Angular dans le conteneur
RUN echo "Copie des fichiers de l'application Angular dans le conteneur..."
COPY . .


RUN echo "Installation des dépendances..."
RUN npm install

RUN echo "Construction de l'application Angular..."
RUN ng build --prod


FROM nginx:alpine


RUN echo "Copie des fichiers construits dans nginx..."
COPY --from=build /app/dist /usr/share/nginx/html

# Exposer le port 80
EXPOSE 80


RUN echo "lancement du conteneur"
CMD ["nginx", "-g", "daemon off;"]